version: '3.8'

services:
  app:
    build: .
    container_name: php_apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: crud_app
      MYSQL_USER: crud_user
      MYSQL_PASSWORD: Crud_Password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  node:
    image: node:18
    container_name: node_app
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: tail -f /dev/null
    ports:
      - "3000:3000"
